controllers/nurseController.js, models/nurse.js
Need to store the token for push notification based on device.
=> Update nurse field to have push notification token

.env.local, controllers/smartWearable.js, index.js, middleware/socket.js, models/smartWearable.js, node_modules/.package-lock.json, package-lock.json, package.json, routes/smartWearable.js
1. Add getSmartWearableBySerialNumber that will be called on the watchOS side to get patient details
2. Set up web socket connections between dvs and smart watch to transmit data
Will require watchOS app to test, will demo to you guys irl.
Will require watchOS app to test, will demo to you guys irl.
=> Feat web socket connection

controllers/vitalController.js, middleware/socket.js
Save the patient vitals from watch as a vital object.
1. Separated the concerns of processing vital data and sending a response in vitalController so that I can persist the vitals received from the wearables in socket.js.
=> Feat save patient vitals from watch

controllers/virtualNurseController.js, index.js, models/nurse.js, models/user.js, models/webUser.js, routes/auth.js, routes/virtualNurse.js
**Added name attribute to user schema**
- updated virtual nurse/nurse schema accordingly
- updated register API
**Edited virtual nurse API**
- created routes for virtual nurse controller
=> Update user models and api

controllers/virtualNurseController.js, index.js, models/user.js, routes/virtualNurse.js
=> Vns 025 added get virtual nurse by

controllers/userController.js, controllers/virtualNurseController.js, controllers/wardController.js, models/ward.js, routes/virtualNurse.js
**Ward Model**
- added new attribute for virtual nurse
**Ward Controller**
- getWards method can now get wards that are assigned to or not assigned to virtual nurses
**Virtual Nurse Controller**
- updated create and update methods to handle relationship between vn and wards
**User Controller**
- removed update method, can use the respective user's update method in their controller
Please provide any additional context or information e.g. screenshots, videos about this pull request if …
=> Virtual Nurse to Ward Bidirectional Relationship Update

controllers/virtualNurseController.js
=> Added getWardsByVirtualNurse API

controllers/virtualNurseController.js, controllers/wardController.js, routes/virtualNurse.js, routes/ward.js
AssignVirtualNurseToWard API
- adds newvirtualnurse-to-ward tagging
- removes oldvirtualnurse-to-ward tagging
=> Created AssignVirtualNurseToWard api

controllers/wardController.js
=> added population of vn to getWards

controllers/patientController.js, middleware/socket.js, models/patient.js, node_modules/.package-lock.json
this is to enable the saving of the layouts of the charts (after customisation). it comes with a default layout.
also added fields to support persistence of fields such as bp, spo2
=> Dvs layout customisation + persistence of vitals

models/patient.js
factor in bp graph when laying out the default config
=> updated default layout to include bp sys

controllers/chatController.js, index.js, models/chat.js, routes/chat.js
=> [CHAT] Add chat messaging feature

controllers/chatController.js, models/chat.js
Add patient in to chat backend logic. This is to allow virtual nurse to share the vitals of a patient with a ground nurse.
This is done by allowing a chat message to possess a patient.
=> Add patient into chat

controllers/chatController.js
Populate the alert object into the chat message. This is so that the virtual nurse has access to the alert information to better understand the situation of the ground nurse comment.
=> Add alert into chat message

controllers/reminderController.js
Added a picture field in the Reminder so that it can receive an image.
=> Add picture into Reminder

controllers/chatController.js, controllers/reminderController.js
Added Camera and picture taking feature to allow ground nurse to take pictures for Reminders and Chats.
=> Add take-picture feature

routes/s3.js
the previous endpoint is using GET. But it throws an error because a body is being used. To bypass this, I change the GET to POST
=> Update endpoint for retrieveFileWithPresignedUrl

controllers/chatController.js, controllers/virtualNurseController.js, models/chat.js, routes/chat.js, routes/virtualNurse.js
I added an attribute into chat model. isArchived.
This will make sure that the chat is not deleted permanantly.
When user create a chat that matches up with an archived chat, it will reopen that chat by updating the isArchived to false.
=> Add isArchived in chats

controllers/nurseController.js, models/user.js
Allow user to store pictures in the schema
=> Profile picture feature

middleware/socket.js
Finally, be able to get replies asap through guo jun's web socket implementation.
=> Add functionalities for real time messaging

controllers/alertController.js, controllers/patientController.js, controllers/vitalController.js, models/alert.js
Allow nurse to update patient vitals on the mobile app as well as consciousness and o2intake
=> Update patient vitals and follow up log alerts

controllers/userController.js, controllers/virtualNurseController.js, controllers/wardController.js, helper/auth.js, models/itAdmin.js, models/virtualNurse.js
1. Remove web user model
2. Added it admin and virtual nurse models
=> Remove webuser model

controllers/patientController.js, helper/news2.js, middleware/socket.js
1. Remove web user model
2. Added it admin and virtual nurse models
=> Fix merge conflicts with main

controllers/vitalController.js, index.js, scripts/initialiseDb.js
=> Refactor changes from previous merge

controllers/alertController.js, controllers/vitalController.js, helper/news2.js, index.js, models/alert.js, models/alertConfig.js, models/vital.js
=> Modify alert

models/itAdmin.js, models/virtualNurse.js
=> Add collection name to model

controllers/chatController.js, middleware/socket.js, models/chat.js, models/ward.js
there is a bug with virtualNurse and VirtualNurse. Fixed it
If your changes include modifications that need testi.ng, please provide detailed testing instructions. This can include steps to reproduce the issue you're fixing or steps to validate new features or changes.
=> Update mongo schema virtual nurse

models/alert.js
=> Add alert notes log

controllers/vitalController.js, scripts/initialiseDb.js
=> Fix init db mongoose connection error

controllers/reportController.js, controllers/s3Controller.js, controllers/vitalController.js, models/report.js
1. Change the req.body of retrieveFileWithPresignedUrl route to accept the whole url instead of just the key. String processing is done on the url to separate the bucket and key. This will affect the mobile chat pages.
2. Add url string attribute to report model
=> Fix s3 upload controller logic

controllers/reportController.js
Delete report object from S3 bucket when report is deleted.
=> Delete object from s3 when report deleted

controllers/reportController.js, routes/report.js
Add GET request in Report controller that returns a list of all reports with patient name and NRIC. This method is called in the view all discharge reports page in DVS.
GET localhost:3001/report/patient
=> Add get all patient reports request to report controller

controllers/alertConfigController.js, controllers/alertController.js, controllers/nurseController.js, controllers/patientController.js, models/alert.js
Update Alert Vital Enums and Alert Config controllers, among other smaller fixes in formatting and code.
=> Update alert vital

middleware/socket.js, scripts/simulatePatientVitals.js
=> feat: fall risk population script and socket

controllers/alertController.js, controllers/nurseController.js, controllers/patientController.js, controllers/smartbedController.js, controllers/userController.js, controllers/vitalController.js, controllers/wardController.js, helper/alertNotification.js, helper/auth.js, middleware/socket.js, models/alert.js, models/itAdmin.js, models/nurse.js, models/smartbed.js, routes/alert.js, routes/nurse.js
redelegation logic on the backend
=> Redelegate alert

middleware/socket.js, scripts/simulatePatientVitals.js
- remove patientConnections socket map
- update simulateFallRisk script to get virtual nurse id from patient using getVirtualNurseById
- use dvsClientConnections (socket for Virtual Nurse) to listen for fall risk value changes
-
simulateFallRisk changes
socket changes
merge 之前，请确保您已了解程序中的任何改变。
=> fix: fetch fall risk values using global virtual nurse socket

controllers/alertController.js, controllers/reminderController.js, controllers/vitalController.js, helper/alertNotification.js, helper/pushNotification.js, helper/reminderNotification.js, models/alert.js
Update push notification handling to ensure smooth and robust push notifications to persist for the alert and reminders.
=> Update push notification handling

controllers/nurseController.js, controllers/wardController.js
Update code for get nurses by ward id 
=> Remove some bugs

controllers/wardController.js, middleware/socket.js
Minor bug fix for the ward controller and add it the update virtual nurse to the ward. BUT THIS IS QUESTIONABLE why this is a use case.
Then I also updated the chat socket to standardise with the rest of the DVS by just using clientConnections.
=> Update chat socket to be clientConnections for virtual nurse

controllers/wardController.js
update the old endpoint for getSmartBedByWardId
=> Update api endpoing for getSmartBedsByWardId

controllers/chatController.js, helper/chatNotification.js
Add the handling for chat notifications. 
=> Add push noti for chats

helper/alertNotification.js, helper/chatNotification.js
=> Update smartbed to smartBed

controllers/alertController.js, controllers/nurseController.js, controllers/patientController.js, controllers/smartbedController.js, controllers/wardController.js, helper/admitPatientNotification.js, helper/alertNotification.js, helper/pushNotification.js, middleware/socket.js, models/smartbed.js, routes/patient.js
=> Admit noti

middleware/socket.js
=> Fix virtual nurse id typo

middleware/socket.js, models/smartbed.js
=> fix discharge

middleware/socket.js
=> Delete previous connection if exists

controllers/alertController.js, controllers/nurseController.js, controllers/patientController.js, controllers/s3Controller.js, controllers/smartbedController.js, controllers/vitalController.js, controllers/wardController.js, helper/admitPatientNotification.js, helper/ahDb.js, helper/report.js, middleware/mongoose.js, middleware/sendMockData.js, scripts/simulatePatientVitals.js
=> Remove console logs, and add catching for mongoose connections

middleware/socket.js
=> cllick on alert to redirect to indiv patient's alert

controllers/smartbedController.js, routes/smartbed.js
- add method to smartBedController and route to unset bedAlarmProtocolBreachReason from smartbed object by ID
- this is for removing reason from the object entirely when fall risk drops from High or when bed exit alarm is turned on
=> feat: add method and route to remove bedAlarmProtocolBreachReason from smartbed

controllers/nurseController.js, helper/admitPatientNotification.js, helper/alertNotification.js, helper/reminderNotification.js
=> Fix noti with try catch
